# Generated by Django 5.2.6 on 2025-09-23 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/casestudies/')),
                ('date', models.DateField(blank=True, null=True)),
                ('read_time', models.CharField(blank=True, max_length=50, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('cta_text', models.CharField(blank=True, max_length=100, null=True)),
                ('cta_link', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=150, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('card_content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/services/')),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('page_content', models.JSONField(blank=True, default=list)),
                ('outcome_text', models.CharField(default='..', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_role', models.CharField(max_length=100)),
                ('author_company', models.CharField(max_length=150)),
                ('company_industry', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='images/testimonials/')),
                ('tags', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='CaseStudyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=250)),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('width', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(choices=[('metric-pink', 'Metric Pink'), ('metric-green', 'Metric Green')], max_length=20)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='cms.casestudy')),
            ],
        ),
        migrations.CreateModel(
            name='AboutUsTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_tabs', to='cms.page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceApproach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.JSONField(blank=True, default=list)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='our_approach', to='cms.service')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceForWhom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight_text', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_whom', to='cms.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight_text', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='cms.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceWhy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight_text', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why', to='cms.service')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Section Name', max_length=150)),
                ('title', models.CharField(default='New Section', max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('button_link', models.CharField(blank=True, max_length=100, null=True)),
                ('section_type', models.CharField(choices=[('none', 'None'), ('testimonials', 'Testimonials'), ('case_studies', 'Case Studies'), ('services', 'Services')], default='none', max_length=20)),
                ('case_studies', models.ManyToManyField(blank=True, to='cms.casestudy')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cms.page')),
                ('services', models.ManyToManyField(blank=True, to='cms.service')),
                ('testimonials', models.ManyToManyField(blank=True, to='cms.testimonial')),
            ],
        ),
    ]
