# Generated by Django 5.2.6 on 2025-09-19 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/home/casestudies/')),
                ('date', models.DateField()),
                ('read_time', models.CharField(max_length=50)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_role', models.CharField(max_length=100)),
                ('author_company', models.CharField(max_length=150)),
                ('company_industry', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='images/home/testimonials/')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='cms.section')),
            ],
        ),
        migrations.DeleteModel(
            name='TestimonialElement',
        ),
    ]
