# Generated by Django 5.2.6 on 2025-09-19 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_casestudies_testimonials_delete_testimonialelement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaseStudies',
            new_name='CaseStudy',
        ),
        migrations.RenameModel(
            old_name='Testimonials',
            new_name='Testimonial',
        ),
    ]
