# Generated by Django 5.2.6 on 2025-09-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_aboutustab_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutustab',
            name='page',
        ),
        migrations.AddField(
            model_name='page',
            name='aboutus_tabs',
            field=models.ManyToManyField(blank=True, to='cms.aboutustab'),
        ),
    ]
