# Generated by Django 5.2.6 on 2025-09-23 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_remove_aboutustab_page_page_aboutus_tabs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='aboutus_tabs',
        ),
        migrations.AddField(
            model_name='aboutustab',
            name='page',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='about_tabs', to='cms.page'),
        ),
    ]
