# Generated by Django 5.2.6 on 2025-09-20 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_rename_casestudies_casestudy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudy',
            name='link',
        ),
        migrations.AddField(
            model_name='casestudy',
            name='cta_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='cta_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='CaseStudyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=250)),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('width', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(choices=[('metric-pink', 'Metric Pink'), ('metric-green', 'Metric Green')], max_length=20)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='cms.casestudy')),
            ],
        ),
    ]
