# Generated by Django 5.2.6 on 2025-09-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_remove_page_aboutus_tabs_aboutustab_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('team', models.CharField(choices=[('core', 'Core'), ('advisor', 'Advisor')], max_length=20)),
                ('image', models.ImageField(upload_to='images/team/')),
                ('linkedin', models.URLField(blank=True, max_length=500)),
            ],
        ),
    ]
