# Generated by Django 5.2.6 on 2025-09-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_remove_casestudy_link_casestudy_cta_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='read_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
