# Generated by Django 5.2.6 on 2025-09-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_casestudy_date_alter_casestudy_read_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='section',
        ),
        migrations.AddField(
            model_name='section',
            name='case_studies',
            field=models.ManyToManyField(blank=True, to='cms.casestudy'),
        ),
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('testimonials', 'Testimonials'), ('case_studies', 'Case Studies')], default='Choose Section Type', max_length=20),
        ),
        migrations.AddField(
            model_name='section',
            name='testimonials',
            field=models.ManyToManyField(blank=True, to='cms.testimonial'),
        ),
    ]
