# Generated by Django 5.2.6 on 2025-09-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_remove_testimonial_section_section_case_studies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('testimonials', 'Testimonials'), ('case_studies', 'Case Studies')], default='testimonials', max_length=20),
        ),
    ]
