# Generated by Django 5.2.6 on 2025-09-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_alter_section_section_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('none', 'None'), ('testimonials', 'Testimonials'), ('case_studies', 'Case Studies')], default='none', max_length=20),
        ),
    ]
