# Generated by Django 5.2.6 on 2025-09-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_alter_section_section_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='order',
        ),
        migrations.RemoveField(
            model_name='section',
            name='section_name',
        ),
        migrations.AddField(
            model_name='section',
            name='name',
            field=models.CharField(default='Section Name', max_length=150),
        ),
    ]
